config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :users

  # Defines the root path route ("/")
  root "landing#index"
  get "agent", to: "agent#index"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :plants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/plant.rb
class Plant < ApplicationRecord
	enum :brightness, {low_brightness: 0, med_low_brightness: 1, med_bright_brightness: 2, bright_brightness: 3}
	enum :watering, {light_watering: 0, med_watering: 1, heavy_watering: 2}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :plants
end

app/controllers/agent_controller.rb
class AgentController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :cors_preflight_check, :cors_set_access_control_headers
  # before_action :cors_set_access_control_headers

  # For all responses in this controller, return the CORS access control headers.

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end

  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.

  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
    # render :text => '', :content_type => 'text/plain'
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: %i[ show edit update destroy ]

  # GET /plants or /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1 or /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants or /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1 or /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: "Plant was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1 or /plants/1.json
  def destroy
    @plant.destroy!

    respond_to do |format|
      format.html { redirect_to plants_path, notice: "Plant was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.expect(plant: [ :name ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :username ])
    end
end

app/helpers/agent_helper.rb
module AgentHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/agent/index.html.erb
<div id="sprigster-agent">
  <h1>agent</h1>
    <script async
      src="https://kdhug52nqlefmuoapafyfzwl.agents.do-ai.run/static/chatbot/widget.js"
      data-agent-id="fc21be7d-a13e-11f0-b074-4e013e2ddde4"
      data-chatbot-id="VGR8s9SXLiern3BzWUpw7MmlpqqN341I"
      data-name="Spigster Chatbot"
      data-primary-color="#D97E96"
      data-secondary-color="#D97E96"
      data-button-background-color="#EFDBDD"
      data-starting-message="Hi, I'm your Sprigster chatbot! What are you plant pondering about?"
      data-logo="/static/chatbot/icons/default-agent.svg">
  </script>
</div>

app/views/landing/index.html.erb
<div id="sprigster-landing">
  <div class="logo">
    <%= image_tag "logo.svg", :class => "logo" %>
    <h1>sprigster</h1>
  </div>
  <%= link_to plants_path, :class => "get-started" do %>
    <div class="button arrow">get started <span>➜</span></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sprigster" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fascinate&family=Manrope:wght@200..800&family=Petrona:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/_form.html.erb
<%= form_with(model: plant) do |form| %>
  <% if plant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>

    <%= form.label :brightness, style: "display: block" %>
    <%= form.text_field :brightness %>

    <%= form.label :watering, style: "display: block" %>
    <%= form.text_field :watering %>

    <%= form.label :toxic, style: "display: block" %>
    <%= form.text_field :toxic %>

    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/_plant.html.erb
<div id="sprigster-plant">
  <div id="<%= dom_id plant %>" class="plant">
    <%= image_tag "logo.svg", :class => "plant-icon" %>
    <div class="plant-details">
      <h2><%= plant.name %></h2>
      <div class="field">
        <strong>Light level needed:</strong>
        <% if plant.low_brightness? %>
          <span>Low light</span>
          <%= image_tag "bright.svg", :class => "field-icon" %>
        <% elsif plant.med_low_brightness? %>
          <span>Indirect light</span>
          <%= image_tag "bright.svg", :class => "field-icon" %>
          <%= image_tag "bright.svg", :class => "field-icon" %>
        <% elsif plant.med_bright_brightness? %>
          <span>Bright indirect light</span>
          <%= image_tag "bright.svg", :class => "field-icon" %>
          <%= image_tag "bright.svg", :class => "field-icon" %>
          <%= image_tag "bright.svg", :class => "field-icon" %>
        <% elsif plant.bright_brightness? %>
          <span>Bright direct light</span>
          <%= image_tag "bright.svg", :class => "field-icon" %>
          <%= image_tag "bright.svg", :class => "field-icon" %>
          <%= image_tag "bright.svg", :class => "field-icon" %>
          <%= image_tag "bright.svg", :class => "field-icon" %>
        <% end %>
      </div>
      <div class="field">
        <strong>Watering schedule:</strong>
        <!--%= plant.watering %-->
        <% if plant.light_watering? %>
          <span>Once a week</span>
          <%= image_tag "water.svg", :class => "field-icon" %>
        <% elsif plant.med_watering? %>
          <span>Twice a week</span>
          <%= image_tag "water.svg", :class => "field-icon" %>
          <%= image_tag "water.svg", :class => "field-icon" %>
        <% elsif plant.heavy_watering? %>
          <span>Multiple times per week</span>
          <%= image_tag "water.svg", :class => "field-icon" %>
          <%= image_tag "water.svg", :class => "field-icon" %>
          <%= image_tag "water.svg", :class => "field-icon" %>
        <% end %>
      </div>
      <div class="field">
        <strong>Pet-friendly:</strong>
        <!--%= plant.toxic %-->
        <% if plant.toxic? %>
          <span>No</span>
          <%= image_tag "toxic-yes.svg", :class => "field-icon" %>
        <% else %>
          <span>Yes</span>
          <%= image_tag "toxic-no.svg", :class => "field-icon" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/plants/edit.html.erb
<% content_for :title, "Editing plant" %>

<h1>Editing plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Show this plant", @plant %> |
  <%= link_to "Back to plants", plants_path %>
</div>

app/views/plants/index.html.erb
<div id="sprigster-plants">
  <p style="color: green"><%= notice %></p>

  <% content_for :title, "Plants" %>

  <h1>Plants</h1>

  <div class="plants">
    <% @plants.each do |plant| %>
      <%= render plant %>
      <!--p-->
        <!--%= link_to "Show this plant", plant %-->
      <!--/p-->
    <% end %>
  </div>

  <!--%= link_to "New plant", new_plant_path %-->
</div>

<script async
  src="https://kdhug52nqlefmuoapafyfzwl.agents.do-ai.run/static/chatbot/widget.js"
  data-agent-id="fc21be7d-a13e-11f0-b074-4e013e2ddde4"
  data-chatbot-id="VGR8s9SXLiern3BzWUpw7MmlpqqN341I"
  data-name="Spigster Chatbot"
  data-primary-color="#D97E96"
  data-secondary-color="#D97E96"
  data-button-background-color="#EFDBDD"
  data-starting-message="Hi, I'm your Sprigster chatbot! What plant questions do you have?"
  data-logo="https://adelemcdonald.com/img/sprigster.svg">
</script>

app/views/plants/new.html.erb
<% content_for :title, "New plant" %>

<h1>New plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Back to plants", plants_path %>
</div>

app/views/plants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plant %>

<div>
  <%= link_to "Edit this plant", edit_plant_path(@plant) %> |
  <%= link_to "Back to plants", plants_path %>

  <%= button_to "Destroy this plant", @plant, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user-field">
    <%= form.label :username, class: "label", style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <%= form.submit "see some plants!", class: "button" %>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<div id="sprigster-new-user">
  <% content_for :title, "Sign up" %>

  <h1>Sign up</h1>

  <%= render "form", user: @user %>

  <br>

  <!-- div-->
    <!--%= link_to "Back to users", users_path %-->
  <!--/div-->
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>